### ISSUE TITLE
Support for localRepository

### ISSUE THREAD

**Issue by balbusm** [puniverse/capsule-maven#12]
Please add support to localRepository defined in settings.xml
Currently capsule-maven is looking for artifacts in ~/.m2/repository even localRepository is different.

**Comment by pron** [comment]
I think that the fastest way to get this done would be to submit a PR. The local repo is set [on this line](https://github.com/puniverse/capsule-maven/blob/master/src/main/java/capsule/DependencyManager.java#L114), and the user settings file is read [here](https://github.com/puniverse/capsule-maven/blob/master/src/main/java/capsule/UserSettings.java).

**Comment by circlespainter** [comment]
`1.0.2-SNAPSHOT` including this enhancement now available on SonaType.
