### ISSUE TITLE
Resolve dependencies from embedded dependencies pom.xml

### ISSUE THREAD

**Issue by chrisdchristo** [puniverse/capsule-maven#14]
Dependency info is essentially declared in three places; the manifest file, the root `pom.xml` and finally the embedded dependencies. What I mean by the latter is by embedding a jar within the capsule, you're essentially saying that the capsule requires this jar and thus logically, the capsule will need all of that jar's dependencies also.

This particularly helps in the scenario where users want to embed only direct dependencies without transitive dependencies as discussed [here](https://github.com/chrischristo/capsule-maven-plugin/issues/44) and [here](https://github.com/chrischristo/capsule-maven-plugin/issues/28).

In light of the [discussion here](https://github.com/puniverse/capsule/issues/102) it makes sense to also have the maven caplet look for dependencies from the embedded jar's `pom.xml`.

**Comment by circlespainter** [comment]
@chrischristo Do you know if there's a quick way to test with a local `capsule-maven` snapshot? [+edit] I've seen there's a sample project already in one of the `capsule-maven-plugin` issues but I can't let the plugin use a `capsule-maven` version installed only locally (`1.0.2-SNAPSHOT`).

[+edit] Not very important, found another way.

**Comment by chrisdchristo** [comment]
thanks, will check it out.
