### ISSUE TITLE
Authentication information in settings.xml not used when accessing remote repositories

### ISSUE THREAD

**Issue by supercargo** [puniverse/capsule-maven#17]
The docs indicate that this should work, but I'm unable to get authentication information for my private repositories to be used when capsule tries to download artifacts from them.  I was able to fix this issue but it required a code change to capsule-maven.  I'm not sure if my fix is correct so I'm opening this issue to make sure there isn't some other problem before opening a PR.

The following change to `DependencyManager` makes the problem go away:
https://github.com/supercargo/capsule-maven/commit/954c5e759c9f3a56141b4210f963fae421ec5e88

**Comment by pron** [comment]
Oh, so the authentication isn't taken automatically from the selector in the session?

**Comment by supercargo** [comment]
Do you mean you expect the authentication information to be available via the session as passed, for example, on this line? https://github.com/puniverse/capsule-maven/blob/9114e1c8ee31caad1d8a90a50b8a581a0e934778/src/main/java/capsule/DependencyManager.java#L360

I don't know enough about Aether to say if this should be working, but empirically no, it fails to use the authentication information (which I confirmed with a packet trace of http requests being made) unless I explicitly wire it in as shown in the patch.  My change followed in the footsteps of what looks like a similar issue around proxy servers?  If that code hadn't been there already I probably wouldn't have figured out where to begin with this.

**Comment by pron** [comment]
Fixed, according to your suggestions. Thanks! (uploaded to snapshots)
