### ISSUE TITLE
Should register artifacts for mvn install and mvn deploy or update documentation

### ISSUE THREAD

**Issue by tngmech** [puniverse/capsule-maven#6]
When following the documentation https://github.com/chrischristo/capsule-maven-plugin to include the plugin during builds the plugin creates e.g. the capsule-fat.jar into the target folder as expected. However the e.g. capsule-fat.jar artifact will not be installed to the local .m2 maven repo with mvn install nor will it be uploaded to e.g. Nexus during mvn deploy.
Other plugins like maven-assembly seem to register their e.g. jar-with-dependencies.jar artifact automatically. For capsule one can make things work when adding the following to the pom.xml:

```
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>build-helper-maven-plugin</artifactId>
  <version>1.7</version>
  <executions>
    <execution>
      <id>attach-artifacts</id>
      <phase>package</phase>
      <goals>
        <goal>attach-artifact</goal>
      </goals>
      <configuration>
        <artifacts>
          <artifact>
            <file>${project.build.directory}/${project.artifactId}-${project.version}-capsule-fat.jar</file>
            <type>jar</type>
            <classifier>capsule-fat</classifier>
          </artifact>
        </artifacts>
      </configuration>
    </execution>
  </executions>
</plugin>
```

It would be great to either have the artifacts registered automatically thru the capsule plugin or add this snippet to the documentation to relief other users from searching stackoverflow.

**Comment by pron** [comment]
Wrong project. This issue belongs in [capsule-maven-plugin](https://github.com/chrischristo/capsule-maven-plugin).

**Comment by tngmech** [comment]
thx. changed project. Will try with the Capsule 1.0-rc1.
