### ISSUE TITLE
For a Java 7 maven project capsule-maven 0.10.4 fails with Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by tngmech** [puniverse/capsule-maven#7]
In contrast to capsule-maven 0.10.3 a Maven project still using Java 7 fails with a message during the build that the class version is unsupported. 52.0 ist Java 8, so probably from 0.10.3 to 0.10.4 the compiler level was changed. This issue should be reproducible with a real JDK 7 installation by just flipping the versions between 0.10.3 and 0.10.4.
It would be great to have Java 7 still supported for a build.

**Comment by tngmech** [comment]
I have seen a stale capsule jdk8 branch with gradle being set to Java 8 while master is Java 7 (again). 
Probably the maven plugin 0.10.4 pulls that JDK8 version accidentally.

**Comment by pron** [comment]
Wrong project. This issue belongs in [capsule-maven-plugin](https://github.com/chrischristo/capsule-maven-plugin) or possibly [Capsule](https://github.com/puniverse/capsule). In any case, Capsule 1.0-rc1 is the version you should use.

**Comment by tngmech** [comment]
Compare: https://github.com/chrischristo/capsule-maven-plugin/issues/24
